apiVersion: apps/v1
kind: Deployment
metadata:
  name: uto-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auto-app
  template:
    metadata:
      labels:
        app: auto-app
    spec:
      containers:
        - name: my-auto-app-newversion
          image: automationapp:v2
          ports:
            - containerPort: 8082