apiVersion: v1
kind: Service
metadata:
  name: my-service-auto-app
  labels:
    app: my-service-auto-app
    app.kubernetes.io/part-of: automation
  annotations:
    prometheus.io/port: "auto-api"
    prometheus.io/scrape: "true"
spec:
  selector:
    app: auto-app
  ports:
    - protocol: TCP
      port: 8082
      name: auto-api
      targetPort: 8082
  type: NodePort
