apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: auto-service-monitor
  namespace: default
spec:
  endpoints:
    - interval: 15s
      port: auto-api
      scrapeTimeout: 14s
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      app.kubernetes.io/part-of: automation
